//
// Created by jantonio on 30/1/22.
//
#include <string.h>
#include <time.h>
#include <openssl/md5.h>
#include <security/pam_modules.h>

#include "url.h"
#include "cas.h"
#define __DIT_UPM_C__
#include "dit_upm.h"

#define DEBUG 1
#define DEBUG_CONTENT 1

/**
 * extract user name from cas received data
 * @return user name or null on faillure
 */
static char *getUserName(struct string *data) {
    return NULL;
}

/**
 * extract full name from cas received data
 * @return gecos or null on faillure
 */
static char *getGecos(struct string *data) {
    return NULL;
}

/**
 * extract user ID from CAS data
 * make sure that uid is greater than 32768, to avoid collision with ldap users uid
 * @param cas_data
 * @return user id or -1 on error
 */
static int getUserID(struct string *data) {
    return -1;
}

/**
 * extract primary group id from CAS received data
 * @param cas_data
 * @return primary group id ( student, teacher, staff, other ), or -1 on error
 */
static int getGroupID(struct string *data) {
    return 0;
}

/**
 * extract alternate groups for given user
 * @param cas_data
 * @return
 */
static int *getGroups(struct string *data) {
    static int groups[16];
    memset(groups,0,sizeof(groups));
    return groups;
}

/**
 * check if user belongs to ETSIT-UPM and is member of any allowed group members
 * @param cas_data
 * @return 1:allowed 0:notAllowed -1:error
 */
static int isAllowed(struct string *data) {
    return 0;
}

/**
 * Check if user directory exists.
 *  if exists, return userdir current userid
 *  else create with provided userid
 *  return resulting home's userid
 * @param username name used to check /home/<username>
 * @param uid evaluated user id from CAS server
 * @param gid evaluated group id from CAS server
 * @return home's userID, -1:error
 */
static int checkAndCreateHome(char *username, int uid, int gid) {
    return uid;
}

/**
 * CAS spec says that login ticket is optional, and may or not be generated by server.
 * So let's us create one when server does not provide us it
 * login is created as "LT-" plus md5 sum of username+time
 * @param user
 * @param pw
 * @param lt
 * @param size
 * @return 0:error 1:success
 */
int ditupm_generateLoginTicket(char *user, char *lt, size_t size) {
    MD5_CTX c;
    char buff[512];
    unsigned char md5[MD5_DIGEST_LENGTH];
    memset(buff,0,sizeof(buff));
    memset(lt,0,size);
    snprintf(buff,sizeof(buff),"%s-%ld",user,time(NULL));
    MD5_Init(&c);
    MD5_Update(&c, buff, strlen(buff));
    MD5_Final(md5, &c);
    sprintf(lt,"LT-");
    for( int n=0;n<MD5_DIGEST_LENGTH;n++) {
        sprintf(lt+strlen(lt),"%02X",md5[n]);
    }
    LOG_MSG(LOG_DEBUG, "evaluated login ticket is: %s\n", lt);
    return 1;
}

/**
 * After user/pass auth success, check if user meets requirements to login into Dit-UPM students labs
 * @param args results from CAS server auth request
 * @return 1:success, 0:faillure, -1:error
 */
int ditupm_check(struct string *args) {
    // first of all check membresy
    int res=isAllowed(args);
    if (res!=1) return res;
    // extract user name, gecos, userid, gid and secondary groups
    char *username= getUserName(args);
    if (!username) return -1;
    char *gecos= getGecos(args);
    if (!gecos) return -1;
    int userid= getUserID(args);
    if (userid<=0) return -1;
    int groupid= getGroupID(args);
    if (groupid<=0) return -1;
    int *groups= getGroups(args);
    if (!groups[0]) return -1;
    // now check for home
    res=checkAndCreateHome(username, userid,groupid);
    if (res<0) return -1;
    userid=res;
    // populate pam structs with evaluated data
    // pending
    // and return success
    return PAM_SUCCESS;
}

/**
 * get received parameters from CAS login request, and prepare it to be parsed
 * @return parsed data
 */
char **eval_receivedCASData(struct string  *args){
    return NULL;
}


/* end of file */
#undef __DIT_UPM_C__